### ISSUE TITLE
wrong opcode base used.

### ISSUE THREAD

**Issue by llde** [FeanorTheElf/obse_nehrim_steam#1]
Hi:
To obse_nehrim plugin was assigned the opcode range 0x28E0-0x28EF however the isngle command provided by this plugin use the default opcode.
This is discouraged and bad practice.
I strongly suggest to use the proper opcode range.

Relevant code:

        obse->SetOpcodeBase(0x2000)
 	obse->RegisterCommand(&kCommandInfo_UnlockAchievement);

**Comment by FeanorTheElf** [comment]
Thank you for the hint, the problem is fixed.
